# Generated by Django 4.2.1 on 2023-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_rename_totalmarks_totalmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmark',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
